    services:
        python:
            image: youtubeimagen:chromecast
            volumes:
                - ./app:/usr/src/app
            stdin_open: true
            tty: true
            command: python